title: Bahasa
description: >-
  Dalam Pelajaran ini siswan di harapkan mampu memahami sesuatu ataupun nilai
  lainnya dari suatu kata atau susunan kata yang menjadi kalimat. Dalam
  melakukan penyusunan kalimat para siswa yang baik biasa dapat embeded yang
  baik pula, kami biasa menyembutnya
steps:
  - course: githubtraining/introduction-to-github
    description: The first step in your course
  - link: 'https://lab.github.com'
    title: Check out Learning Lab for more courses!
    description: >-
      There are many more courses available on Learning Lab for you to check
      out.
